function aiText(element){return state.lang==='vi'?element.dataset.aiVi:element.dataset.aiEn}
function renderAI(){
 document.querySelectorAll('[data-ai-vi]').forEach(el=>{el.textContent=aiText(el)});
 const insights=state.report?.insights||{};const rows=insights.opportunities||[];
 $('#opportunityUnavailable').hidden=rows.length>0;$('#dailyThesis').textContent=state.lang==='vi'?(insights.daily_thesis_vi||''):(insights.daily_thesis_en||'');
 $('#opportunityGrid').innerHTML=rows.map(row=>{const name=state.lang==='vi'?row.name_vi:row.name_en;const pain=state.lang==='vi'?row.pain_vi:row.pain_en;const audience=state.lang==='vi'?row.audience_vi:row.audience_en;const sources=(row.sources||[]).map(source=>`<a href="${esc(source.url)}" target="_blank" rel="noopener">${esc(source.source)} — ${esc(source.title)}</a>`).join('');return `<article class="opportunity-card"><header><span class="scope">${esc(row.scope)}</span><div class="score-ring" style="--score:${Number(row.score)||0}"><span>${Number(row.score)||0}</span></div></header><h3>${esc(name)}</h3><p>${esc(pain)}</p><p><strong>${state.lang==='vi'?'Khách hàng:':'Audience:'}</strong> ${esc(audience)}</p><details><summary>${state.lang==='vi'?'Bằng chứng':'Evidence'} (${(row.sources||[]).length})</summary>${sources}</details></article>`}).join('');
}
window.renderAI=renderAI;
const chatPanel=$('#chatPanel'),backdrop=$('#chatBackdrop'),messages=$('#chatMessages'),chatInput=$('#chatInput');
function toggleChat(open){chatPanel.classList.toggle('open',open);chatPanel.setAttribute('aria-hidden',String(!open));backdrop.hidden=!open;if(open)setTimeout(()=>chatInput.focus(),100)}
function addMessage(kind,text,sources=[]){const node=document.createElement('div');node.className=`${kind}-message`;node.innerHTML=`<p>${esc(text)}</p>`+(sources.length?`<div class="chat-sources">${sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">[${s.id}] ${esc(s.source)} — ${esc(s.title)}</a>`).join('')}</div>`:'');messages.appendChild(node);messages.scrollTop=messages.scrollHeight;return node}
$('#openChat').addEventListener('click',()=>toggleChat(true));$('#closeChat').addEventListener('click',()=>toggleChat(false));backdrop.addEventListener('click',()=>toggleChat(false));
document.addEventListener('keydown',event=>{if(event.key==='Escape')toggleChat(false)});
document.querySelectorAll('[data-prompt-vi]').forEach(button=>button.addEventListener('click',()=>{chatInput.value=state.lang==='vi'?button.dataset.promptVi:button.dataset.promptEn;chatInput.focus()}));
$('#chatForm').addEventListener('submit',async event=>{event.preventDefault();const question=chatInput.value.trim();if(!question)return;addMessage('user',question);chatInput.value='';const typing=document.createElement('div');typing.className='ai-message typing';typing.innerHTML='<i></i><i></i><i></i>';messages.appendChild(typing);messages.scrollTop=messages.scrollHeight;try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,language:state.lang,date:state.report?.date})});const payload=await response.json();typing.remove();if(!response.ok)throw new Error(payload.error||'AI unavailable');addMessage('ai',payload.answer,payload.sources)}catch(error){typing.remove();addMessage('ai',`${state.lang==='vi'?'Không thể trả lời lúc này:':'Unable to answer now:'} ${error.message}`)}});
